import flet as ft
import edge_tts, os, json, random, asyncio
from dotenv import load_dotenv
from cerebras.cloud.sdk import AsyncCerebras

from setup import setup_page, FontStyles, PC_PLATFORMS
from audio.audio_manager import AudioManager

def get_api_key():
    key = os.getenv("CEREBRAS_API_KEY")
    if key: return key
    
    try:
        # Build the path relative to THIS file (main.py)
        base_dir = os.path.dirname(__file__)
        secret_path = os.path.join(base_dir, "assets", "secret.json")
        
        # Fallback: Flet sometimes sets a specific environment variable for assets
        flet_assets = os.getenv("FLET_ASSETS_DIR", "assets")
        if not os.path.exists(secret_path):
            secret_path = os.path.join(base_dir, flet_assets, "secret.json")
            
        with open(secret_path, "r", encoding="utf-8") as f:
            secret = json.load(f)
            return secret.get("CEREBRAS_API_KEY")
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Asset lookup failed: {e}")
        pass
    
    load_dotenv()
    return os.getenv("CEREBRAS_API_KEY")

# TODO: Make this autogenerated from the json data
HSK1_WORDS = [
    {"char": "爱", "pinyin": "ài", "translation": "love"},
    {"char": "医生", "pinyin": "yīshēng", "translation": "doctor"},
    {"char": "漂亮", "pinyin": "piàoliang", "translation": "pretty"},
    {"char": "猫", "pinyin": "māo", "translation": "cat"},
    {"char": "水果", "pinyin": "shuǐguǒ", "translation": "fruit"},
    {"char": "谢谢", "pinyin": "xièxie", "translation": "thanks"},
]

# TODO: Add more difficulties
# HSK2_WORDS = []
# HSK3_WORDS = []

# TODO: Make the sentence example optional
async def get_lesson_data(client: AsyncCerebras):
    base_word = random.choice(HSK1_WORDS)
    
    system_p = (
        "You are a Chinese teacher. Return ONLY a JSON object. "
        "CRITICAL: Do not use Unicode escape sequences. Use raw UTF-8 Chinese characters. "
        "If you cannot return valid Chinese, return an empty string. "
        "Format: {'example': 'Chinese here', 'example_eng': 'English here'}"
    )
    user_p = f"Create a very simple beginner sentence using the word '{base_word['char']}'."
    
    try:
        response = await client.chat.completions.create(
            model="gpt-oss-120b",
            messages=[
                {"role": "system", "content": system_p},
                {"role": "user", "content": user_p}
            ],
            stream=False,
            response_format={"type": "json_object"}
        )
        content_raw = response.choices[0].message.content
        print(f"Received: {json.dumps(json.loads(content_raw), ensure_ascii=False, indent=2)}")
        content: dict[str, str] = json.loads(content_raw.encode("utf-8").decode("utf-8"))
        print(f"Generated: {content}")
        return {
            "char": base_word.get("char", "水"),
            "pinyin": base_word.get("pinyin", "shuǐ"),
            "translation": base_word.get("translation", "water"),
            "example": content.get("example", "我喝水。"),
            "example_eng": content.get("example_ts", "I'm drinking water.")
        }
    
    except Exception as e:
        return {**base_word, "example": "Content loading...", "error": str(e)}

async def get_audio_bytes(text: str) -> bytes:
    communicate = edge_tts.Communicate(text, "zh-CN-XiaoxiaoNeural", rate="-50%")
    audio_data = bytearray()
    
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            audio_data.extend(chunk["data"]) # 'data' contains the raw bytes
            
    return bytes(audio_data)

async def is_api_key_valid(client: AsyncCerebras) -> bool:
    try:
        # A tiny request to "probe" the server
        await client.chat.completions.create(
            model="llama3.1-8b", 
            messages=[{"role": "user", "content": "hi"}],
            max_tokens=1 
        )
        return True
    except Exception as e:
        # If it returns a 401 Unauthorized, the key is invalid
        print(f"Validation failed: {e}")
        return False

async def api_check(page: ft.Page) -> str:
    validated_event = asyncio.Event()
    validated_key: str = ""
    
    async def validate(_) -> None:
        nonlocal validated_key
        tf.error = None
        tf.update()
        
        if tf.value in [None, "", " "]:
            tf.error = "Key Cannot be Empty"
            tf.update()
            return
        
        test_client = AsyncCerebras(api_key=tf.value)
        
        if await is_api_key_valid(test_client):
            validated_key = tf.value
            tf.error = None
            tf.update()
            await ft.SharedPreferences().set("cerebras_api_key", tf.value)
            page.pop_dialog()
            validated_event.set()
        else:
            tf.error = "Invalid Key"
            tf.update()
            
    tf = ft.TextField(
        hint_text="Enter Cerebras Key", password=True, can_reveal_password=True,
        on_submit=validate
    )
    
    modal_dialog = ft.AlertDialog(
        modal=True,
        title="Authentication Required",
        content=tf,
        actions=[ft.Button("Validate", on_click=validate)],
    )
    
    page.show_dialog(modal_dialog)
    await validated_event.wait()
    return validated_key

async def main(page: ft.Page) -> None:
    setup_page(page)
    status_txt = ft.Text("Starting Setup... 1/2")
    page.add(ft.ProgressRing(), status_txt)
    if page.platform in PC_PLATFORMS:
        await page.window.center()
    
    def change_status(text: str) -> None:
        nonlocal status_txt
        status_txt.value = text
        status_txt.update()
    
    change_status("Starting local service...")
    prefs = ft.SharedPreferences()
    change_status("Getting API key...")
    api_key = get_api_key()
    
    if api_key is None:
        change_status("Checking for API key...")
        if await prefs.contains_key("cerebras_api_key"):
            change_status("Using saved API key...")
            api_key = await prefs.get(key="cerebras_api_key")
    
    if api_key is None:
        change_status("Awaiting API key...")
        api_key = await api_check(page)
    
    change_status("Starting client...")
    client = AsyncCerebras(api_key=api_key)
    
    change_status("Finishing Setup... 2/2")
    audio_manager = AudioManager(page)
    audio_bytes: bytes = None
    audio_bytes = await get_audio_bytes("按下开始")
    
    # UI Components
    char_display = ft.Text(
        value="按下开始", size=70, weight=ft.FontWeight.BOLD,
        color=ft.Colors.PRIMARY, font_family=FontStyles.NOTO_SANS_SC
    )
    pinyin_display = ft.Text(value="Àn xià kāishǐ", size=25, italic=True, color=ft.Colors.PRIMARY)
    trans_display = ft.Text(value="Press to start", size=20, color=ft.Colors.SECONDARY)
    loading_ring = ft.ProgressRing(visible=False)
    
    async def generate_lesson(_) -> None:
        nonlocal audio_bytes
        loading_ring.visible = True
        loading_ring.update()
        
        data = await get_lesson_data(client)
        
        if "error" not in data:
            char_display.value = data.get("char", "Error")
            pinyin_display.value = data.get("pinyin", "Error")
            trans_display.value = data.get("translation", "Error")
            char_display.update()
            pinyin_display.update()
            trans_display.update()
            
            text_to_speak = str(data.get("example", "")).strip()
            audio_bytes = await get_audio_bytes(text_to_speak)
            
            if audio_bytes:
                audio_manager.play_sfx(audio_bytes)
                
            loading_ring.visible = False
            loading_ring.update()
            
        else:
            loading_ring.visible = False
            loading_ring.update()
            print(f"Cerebras Error: {data['error']}")
    
    async def play_audio(_) -> None:
        if not audio_bytes: return
        audio_manager.play_sfx(audio_bytes)
    
    async def on_reset(_) -> None:
        print("Resetting saved preferences...")
        if await prefs.clear():
            print("Successfully reset saved preferences!")
        else:
            print("Failed resetting saved preferences!")
    
    text_displays = ft.Column(
        controls=[
            char_display,
            pinyin_display,
            trans_display,
        ],
        horizontal_alignment=ft.CrossAxisAlignment.CENTER
    )
    
    button_row = ft.Row(
        controls=[
            ft.Button("New Word", on_click=generate_lesson, height=50),
            ft.IconButton(ft.Icons.VOLUME_UP, on_click=play_audio),
            ft.IconButton(ft.Icons.RESTORE, on_click=on_reset)
        ],
        alignment=ft.MainAxisAlignment.CENTER
    )
    
    main_content = ft.Column(
        controls=[
            ft.Text("VaniLingo", size=30, weight=ft.FontWeight.BOLD),
            ft.Divider(height=50, color=ft.Colors.TRANSPARENT),
            ft.Container(
                content=text_displays,
                padding=30,
                border=ft.Border.all(2, ft.Colors.ON_PRIMARY_CONTAINER),
                border_radius=20,
                bgcolor=ft.Colors.PRIMARY_CONTAINER,
            ),
            loading_ring,
            button_row
        ],
        horizontal_alignment=ft.CrossAxisAlignment.CENTER
    )
    
    change_status("Starting App!")
    await asyncio.sleep(0.1)
    page.controls.clear()
    page.add(ft.SafeArea(main_content))
    page.update()
    audio_manager.play_sfx(audio_bytes)

ft.run(main)